server:
  port: 8080

eureka:
  #instance:
  #prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://routine-eureka:8765/eureka

spring:
  application:
    name: routine-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: TRACE
