server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${eureka.instance.ip-address}:${server.port}
#    instance-id: ${eureka.instance.ip-address}:${random.value}
#    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8765/eureka

spring:
  application:
    name: routine-service

  datasource:
    driver-class-name: ${DB_DRIVER_NAME}
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        use_sql_comments: true

#eureka:
#  client:
#    instance:
#      prefer-ip-address: true
##      ip-address: localhost
#    #      lease-renewal-interval-in-seconds: 30  # 리스 갱신 간격
#    #      lease-expiration-duration-in-seconds: 90  # 리스 만료 기간
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8765/eureka
#      #도커 없는 환경이라 게이트웨이가 LB 이름을 IP 주소로 변환하지 못함
#      #임시로 IP 주소를 명시적으로 적음

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: TRACE