spring:
  application:
    name: routine-service

  datasource:
    driver-class-name: ${DB_DRIVER_NAME}
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          database-platform: org.hibernate.dialect.MariaDB103Dialect
          format_sql: true
          use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: TRACE
